# SPDX-FileCopyrightText: Copyright (c) 2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
  aira-instruct-llm:
    container_name: aira-instruct-llm
    image: nvcr.io/nim/meta/llama-3.3-70b-instruct:latest
    runtime: nvidia
    volumes:
    - ${MODEL_DIRECTORY:-./}:/opt/nim/.cache
    user: "${USERID}"
    ports:
    - "8050:8000"
    expose:
    - "8050"
    environment:
      NGC_API_KEY: ${NGC_API_KEY}
    shm_size: 20gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # RAG uses 0,1 so we assign 2,3 to the LLM
              device_ids: ['${AIRA_LLM_MS_GPU_ID:-2,3}']
              capabilities: [gpu] 
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('http://localhost:8000/v1/health/ready')"]
      interval: 30s
      timeout: 20s
      retries: 100
    networks:
      - nvidia-rag
    profiles: ["aira-instruct-llm"]

  aira-backend:
    container_name: aira-backend
    image: nvcr.io/nvidia/blueprint/aira-backend:v1.1.0
    runtime: nvidia
    build:
      context: ../../
      dockerfile: aira/Dockerfile
    entrypoint: "/entrypoint.sh"
    ports:
      - "3838:3838"
    expose:
      - "3838"
    environment:
      TAVILY_API_KEY: ${TAVILY_API_KEY:-this-is-a-test-key}
      AIRA_APPLY_GUARDRAIL: "false"
      OPENAI_API_KEY: ${NVIDIA_API_KEY:-your-nvidia-api-key}
      AIRA_HOSTED_NIMS: ${AIRA_HOSTED_NIMS:-false}
      # Redis configuration for session management
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SESSION_TIMEOUT_HOURS: ${SESSION_TIMEOUT_HOURS:-24}
    volumes:
      - ../../aira/configs:/app/configs
    networks:
      - nvidia-rag
    depends_on:
      redis:
        condition: service_healthy
    profiles: ["aira"]

  # Redis for session TTL tracking
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    # Enable persistence: save every 60s if 1+ keys changed, AOF enabled
    command: redis-server --save 60 1 --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - nvidia-rag
    profiles: ["aira"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  aira-nginx:
    image: nginx:latest
    container_name: aira-nginx
    ports:
      - "8051:8051"
    expose:
      - "8051"
    environment:
      # Route collections to AIRA, documents directly to RAG
      - RAG_INGEST_URL=${RAG_INGEST_URL:-http://ingestor-server:8082}
      - AIRA_BASE_URL=${AIRA_BASE_URL:-http://aira-backend:3838}
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template
    depends_on:
      - aira-backend
    networks:
      - nvidia-rag
    profiles: ["aira"]

  aira-frontend:
    container_name: aira-frontend
    image: nvcr.io/nvidia/blueprint/aira-frontend:v1.1.0
    ports:
      - "3001:3001"
    expose:
      - "3001"
    networks:
      - nvidia-rag
    environment:
      NVWB_TRIM_PREFIX: true
      INFERENCE_ORIGIN: ${INFERENCE_ORIGIN:-http://aira-nginx:8051}
    profiles: ["aira"]

# Use the nvidia-rag network created by the 
# RAG docker compose deployment
# If you are deploying RAG separately
# set external to false
networks:
  nvidia-rag:
    external: true
    name: nvidia-rag

# Persistent volumes
volumes:
  redis-data:
