{{- if .Values.frontend.enabled }}
{{- if .Values.frontend.ingress.enabled }}
{{- $host := .Values.frontend.ingress.host | default (printf "%s%s" .Release.Namespace .Values.frontend.ingress.domainSuffix) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-aira-frontend
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.frontend.ingress.className }}
    kubernetes.io/ingress.class: {{ .Values.frontend.ingress.className }}
    {{- end }}
    {{- if .Values.frontend.ingress.annotations }}
    {{- range $key, $value := .Values.frontend.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
spec:
  {{- if .Values.frontend.ingress.tls }}
  tls:
    - hosts:
        - {{ $host | quote }}
      secretName: {{ .Values.frontend.ingress.tls.secretName | default (printf "%s-tls" .Release.Namespace) }}
  {{- end }}
  rules:
    - host: {{ $host | quote }}
      http:
        paths:
          {{- range .Values.frontend.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Release.Name }}-aira-frontend
                port:
                  number: {{ $.Values.frontend.service.port }}
          {{- end }}
{{- end }}
{{- end }}
